from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    PAUSED = "PAUSED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class EvaluationCampaignStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_INVALID = "COMPLETED_WITH_INVALID"
    BLOCKED = "BLOCKED"
    INDETERMINATE = "INDETERMINATE"


class EvaluationSlotStatus(StrEnum):
    PENDING = "PENDING"
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    ACCEPTED = "ACCEPTED"
    REPLACEMENT_PENDING = "REPLACEMENT_PENDING"
    INVALID = "INVALID"
    INDETERMINATE = "INDETERMINATE"


class EvaluationAttemptStatus(StrEnum):
    CREATED = "CREATED"
    WORKSPACE_READY = "WORKSPACE_READY"
    RUNTIME_READY = "RUNTIME_READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    INVALID = "INVALID"
    INDETERMINATE = "INDETERMINATE"


class EvaluationOutcomeClass(StrEnum):
    SCORED = "SCORED"
    INFRASTRUCTURE_INVALID = "INFRASTRUCTURE_INVALID"
    INDETERMINATE = "INDETERMINATE"


class EvaluationFailureClass(StrEnum):
    NONE = "NONE"
    MODEL_QUALITY = "MODEL_QUALITY"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    CONFIGURATION = "CONFIGURATION"
    SAFETY_INDETERMINATE = "SAFETY_INDETERMINATE"


class EvaluationStudyStatus(StrEnum):
    DRAFT = "DRAFT"
    AUTHORIZED = "AUTHORIZED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_INFRASTRUCTURE_GAPS = (
        "COMPLETED_WITH_INFRASTRUCTURE_GAPS"
    )
    ABORTED_CONFIGURATION = "ABORTED_CONFIGURATION"
    INDETERMINATE = "INDETERMINATE"


class ModelAttemptStatus(StrEnum):
    PREPARED = "PREPARED"
    DISPATCHING = "DISPATCHING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INDETERMINATE = "INDETERMINATE"


class ModelRecoveryAction(StrEnum):
    DISPATCH = "DISPATCH"
    MARK_INDETERMINATE = "MARK_INDETERMINATE"
    TERMINAL_REPLAY = "TERMINAL_REPLAY"


class EventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    RUN_STARTED = "RUN_STARTED"
    MODEL_REQUESTED = "MODEL_REQUESTED"
    MODEL_RESPONDED = "MODEL_RESPONDED"
    MODEL_ATTEMPT_PREPARED = "MODEL_ATTEMPT_PREPARED"
    MODEL_ATTEMPT_DISPATCHING = "MODEL_ATTEMPT_DISPATCHING"
    MODEL_ATTEMPT_COMPLETED = "MODEL_ATTEMPT_COMPLETED"
    MODEL_ATTEMPT_FAILED = "MODEL_ATTEMPT_FAILED"
    MODEL_ATTEMPT_INDETERMINATE = "MODEL_ATTEMPT_INDETERMINATE"
    MODEL_RETRY_SCHEDULED = "MODEL_RETRY_SCHEDULED"
    MODEL_FAILED = "MODEL_FAILED"
    MODEL_PROVIDER_DEVIATION = "MODEL_PROVIDER_DEVIATION"
    MULTI_TOOL_RESPONSE_NORMALIZED = "MULTI_TOOL_RESPONSE_NORMALIZED"
    CONTEXT_COMPACTED = "CONTEXT_COMPACTED"
    LOOP_WARNING = "LOOP_WARNING"
    LOOP_DETECTED = "LOOP_DETECTED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    TOOL_REQUESTED = "TOOL_REQUESTED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    CHECKPOINT_SAVED = "CHECKPOINT_SAVED"
    RUN_PAUSED = "RUN_PAUSED"
    RUN_RESUMED = "RUN_RESUMED"
    RUN_FAILED = "RUN_FAILED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_CANCELLED = "RUN_CANCELLED"
    MUTATION_REQUESTED = "MUTATION_REQUESTED"
    MUTATION_STARTED = "MUTATION_STARTED"
    MUTATION_COMMITTED = "MUTATION_COMMITTED"
    MUTATION_FAILED = "MUTATION_FAILED"
    MUTATION_INDETERMINATE = "MUTATION_INDETERMINATE"
    TEST_REQUESTED = "TEST_REQUESTED"
    TEST_STARTED = "TEST_STARTED"
    TEST_COMPLETED = "TEST_COMPLETED"
    TEST_FAILED = "TEST_FAILED"
    TEST_TIMEOUT = "TEST_TIMEOUT"
    TEST_CANCELLED = "TEST_CANCELLED"
    TEST_INDETERMINATE = "TEST_INDETERMINATE"
    REPAIR_TASK_STARTED = "REPAIR_TASK_STARTED"
    REPAIR_POLICY_BOUND = "REPAIR_POLICY_BOUND"
    REPAIR_BUDGET_CONSUMED = "REPAIR_BUDGET_CONSUMED"
    REPAIR_POLICY_VIOLATION = "REPAIR_POLICY_VIOLATION"
    REPAIR_COMPLETION_REJECTED = "REPAIR_COMPLETION_REJECTED"
    REPAIR_COMPLETION_CORRECTED = "REPAIR_COMPLETION_CORRECTED"
    WORKSPACE_BASELINE_CREATED = "WORKSPACE_BASELINE_CREATED"
    WORKSPACE_DIFF_VALIDATED = "WORKSPACE_DIFF_VALIDATED"
    WORKSPACE_DIFF_VIOLATION = "WORKSPACE_DIFF_VIOLATION"
    FINAL_VERIFICATION_REQUESTED = "FINAL_VERIFICATION_REQUESTED"
    FINAL_VERIFICATION_COMPLETED = "FINAL_VERIFICATION_COMPLETED"
    FINAL_VERIFICATION_FAILED = "FINAL_VERIFICATION_FAILED"
    REPAIR_TASK_COMPLETED = "REPAIR_TASK_COMPLETED"
    REPAIR_TASK_FAILED = "REPAIR_TASK_FAILED"
    EVALUATION_RUN_STARTED = "EVALUATION_RUN_STARTED"
    EVALUATION_RUN_COMPLETED = "EVALUATION_RUN_COMPLETED"
    AUTO_APPROVAL_GRANTED = "AUTO_APPROVAL_GRANTED"
    AUTO_APPROVAL_DENIED = "AUTO_APPROVAL_DENIED"
    EVALUATION_BASELINE_CREATED = "EVALUATION_BASELINE_CREATED"
    EVALUATION_BASELINE_STARTED = "EVALUATION_BASELINE_STARTED"
    EVALUATION_BASELINE_VERIFIED = "EVALUATION_BASELINE_VERIFIED"
    EVALUATION_BASELINE_BLOCKED = "EVALUATION_BASELINE_BLOCKED"
    EVALUATION_BASELINE_INDETERMINATE = "EVALUATION_BASELINE_INDETERMINATE"
    EVALUATION_BASELINE_CONTEXT_INJECTED = "EVALUATION_BASELINE_CONTEXT_INJECTED"
    EVALUATION_CAMPAIGN_CREATED = "EVALUATION_CAMPAIGN_CREATED"
    EVALUATION_CAMPAIGN_STARTED = "EVALUATION_CAMPAIGN_STARTED"
    EVALUATION_SLOT_CLAIMED = "EVALUATION_SLOT_CLAIMED"
    EVALUATION_ATTEMPT_CREATED = "EVALUATION_ATTEMPT_CREATED"
    EVALUATION_ATTEMPT_WORKSPACE_READY = "EVALUATION_ATTEMPT_WORKSPACE_READY"
    EVALUATION_ATTEMPT_RUNTIME_READY = "EVALUATION_ATTEMPT_RUNTIME_READY"
    EVALUATION_ATTEMPT_STARTED = "EVALUATION_ATTEMPT_STARTED"
    EVALUATION_ATTEMPT_COMPLETED = "EVALUATION_ATTEMPT_COMPLETED"
    EVALUATION_ATTEMPT_INVALID = "EVALUATION_ATTEMPT_INVALID"
    EVALUATION_ATTEMPT_INDETERMINATE = "EVALUATION_ATTEMPT_INDETERMINATE"
    EVALUATION_REPLACEMENT_CREATED = "EVALUATION_REPLACEMENT_CREATED"
    EVALUATION_SLOT_ACCEPTED = "EVALUATION_SLOT_ACCEPTED"
    EVALUATION_SLOT_INVALID = "EVALUATION_SLOT_INVALID"
    EVALUATION_SLOT_INDETERMINATE = "EVALUATION_SLOT_INDETERMINATE"
    EVALUATION_CAMPAIGN_COMPLETED = "EVALUATION_CAMPAIGN_COMPLETED"
    EVALUATION_STUDY_CREATED = "EVALUATION_STUDY_CREATED"
    EVALUATION_STUDY_AUTHORIZED = "EVALUATION_STUDY_AUTHORIZED"
    EVALUATION_STUDY_STARTED = "EVALUATION_STUDY_STARTED"
    EVALUATION_STUDY_CAMPAIGN_COMPLETED = (
        "EVALUATION_STUDY_CAMPAIGN_COMPLETED"
    )
    EVALUATION_STUDY_COMPLETED = "EVALUATION_STUDY_COMPLETED"
    EVALUATION_STUDY_ABORTED = "EVALUATION_STUDY_ABORTED"
    EVALUATION_STUDY_INDETERMINATE = "EVALUATION_STUDY_INDETERMINATE"


class RunFailureCode(StrEnum):
    """Closed, diagnostic-free terminal Run failure classifications."""

    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_INDETERMINATE = "APPROVAL_INDETERMINATE"
    COMMAND_FAILED = "COMMAND_FAILED"
    COMMAND_INDETERMINATE = "COMMAND_INDETERMINATE"
    MUTATION_INDETERMINATE = "MUTATION_INDETERMINATE"
    TEST_PROFILE_MISMATCH = "TEST_PROFILE_MISMATCH"
    TEST_EXECUTION_INDETERMINATE = "TEST_EXECUTION_INDETERMINATE"
    TESTS_FAILED = "TESTS_FAILED"
    FINAL_VERIFICATION_FAILED = "FINAL_VERIFICATION_FAILED"
    UNVERIFIED_FINAL = "UNVERIFIED_FINAL"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    DIFF_POLICY_VIOLATION = "DIFF_POLICY_VIOLATION"
    LOOP_DETECTED = "LOOP_DETECTED"
    MODEL_FAILURE = "MODEL_FAILURE"
    MODEL_PROTOCOL_ERROR = "MODEL_PROTOCOL_ERROR"
    MODEL_TOOL_FAILED = "MODEL_TOOL_FAILED"
    RUNTIME_FAILURE = "RUNTIME_FAILURE"
    INDETERMINATE = "INDETERMINATE"
    CANCELLED = "CANCELLED"


class ConfigSourceKind(StrEnum):
    """Safe public provenance categories for trusted profile configuration."""

    BUILTIN = "BUILTIN"
    PROJECT = "PROJECT"
    FORMAL_MANIFEST = "FORMAL_MANIFEST"
    EVALUATOR = "EVALUATOR"


class ToolRisk(StrEnum):
    READ = "READ"
    WRITE = "WRITE"
    DANGEROUS = "DANGEROUS"


class ToolSource(StrEnum):
    LOCAL = "LOCAL"
    MCP = "MCP"


class ToolCapability(StrEnum):
    NONE = "NONE"
    TEST_PROFILE_EXECUTION = "TEST_PROFILE_EXECUTION"
    CANDIDATE_PATCH_PUBLICATION = "CANDIDATE_PATCH_PUBLICATION"


class WriteMode(StrEnum):
    CREATE_ONLY = "CREATE_ONLY"
    EXPECTED_HASH_REPLACE = "EXPECTED_HASH_REPLACE"


class MutationExecutionStatus(StrEnum):
    PREPARED = "PREPARED"
    WRITING = "WRITING"
    COMMITTED = "COMMITTED"
    FAILED = "FAILED"
    INDETERMINATE = "INDETERMINATE"


class ProcessExecutionStatus(StrEnum):
    CREATED = "CREATED"
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    INDETERMINATE = "INDETERMINATE"


class ProcessFailureKind(StrEnum):
    TEST_FAILURE = "TEST_FAILURE"
    LAUNCH_FAILURE = "LAUNCH_FAILURE"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    PROFILE_MISMATCH = "PROFILE_MISMATCH"
    SUPERVISOR_FAILURE = "SUPERVISOR_FAILURE"
    INDETERMINATE = "INDETERMINATE"


class MultiToolResponsePolicy(StrEnum):
    STRICT = "STRICT"
    SEQUENTIAL_READ_ONLY = "SEQUENTIAL_READ_ONLY"


class PathKind(StrEnum):
    ANY = "ANY"
    FILE = "FILE"
    DIRECTORY = "DIRECTORY"


class PolicyOutcome(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class RejectionStrategy(StrEnum):
    CONTINUE = "CONTINUE"
    FAIL_RUN = "FAIL_RUN"


class ApprovalConsumptionState(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    CLAIMED = "CLAIMED"
    CONSUMED = "CONSUMED"
    INDETERMINATE = "INDETERMINATE"


class ResumePhase(StrEnum):
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    READY_FOR_MODEL = "READY_FOR_MODEL"


class ToolErrorCode(StrEnum):
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    DUPLICATE_TOOL = "DUPLICATE_TOOL"
    INVALID_TOOL_SPEC = "INVALID_TOOL_SPEC"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    POLICY_DENIED = "POLICY_DENIED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_CONFLICT = "APPROVAL_CONFLICT"
    APPROVAL_INDETERMINATE = "APPROVAL_INDETERMINATE"
    RESUME_NOT_ALLOWED = "RESUME_NOT_ALLOWED"
    CHECKPOINT_MISSING = "CHECKPOINT_MISSING"
    CHECKPOINT_CORRUPT = "CHECKPOINT_CORRUPT"
    TOOL_BUDGET_EXCEEDED = "TOOL_BUDGET_EXCEEDED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_CANCELLED = "TOOL_CANCELLED"
    TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
    INVALID_PATH = "INVALID_PATH"
    PATH_OUTSIDE_WORKSPACE = "PATH_OUTSIDE_WORKSPACE"
    PATH_NOT_FOUND = "PATH_NOT_FOUND"
    PATH_TYPE_MISMATCH = "PATH_TYPE_MISMATCH"
    SENSITIVE_PATH = "SENSITIVE_PATH"
    SENSITIVE_CONTENT = "SENSITIVE_CONTENT"
    BINARY_FILE = "BINARY_FILE"
    ENCODING_ERROR = "ENCODING_ERROR"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    MUTATION_TARGET_EXISTS = "MUTATION_TARGET_EXISTS"
    MUTATION_HASH_MISMATCH = "MUTATION_HASH_MISMATCH"
    MUTATION_TEXT_MISMATCH = "MUTATION_TEXT_MISMATCH"
    MUTATION_INDETERMINATE = "MUTATION_INDETERMINATE"
    ATOMIC_WRITE_FAILED = "ATOMIC_WRITE_FAILED"
    INVALID_TEST_PROFILE = "INVALID_TEST_PROFILE"
    TEST_PROFILE_NOT_FOUND = "TEST_PROFILE_NOT_FOUND"
    TEST_PROFILE_DISABLED = "TEST_PROFILE_DISABLED"
    TEST_PROFILE_MISMATCH = "TEST_PROFILE_MISMATCH"
    SOURCE_REVISION_MISMATCH = "SOURCE_REVISION_MISMATCH"
    MANAGED_EXECUTION_REQUIRED = "MANAGED_EXECUTION_REQUIRED"
    REPAIR_POLICY_DENIED = "REPAIR_POLICY_DENIED"
    REPAIR_BUDGET_EXCEEDED = "REPAIR_BUDGET_EXCEEDED"
    NOT_GIT_REPOSITORY = "NOT_GIT_REPOSITORY"
    UNSAFE_REPOSITORY_LAYOUT = "UNSAFE_REPOSITORY_LAYOUT"
    GIT_COMMAND_FAILED = "GIT_COMMAND_FAILED"


ALLOWED_RUN_TRANSITIONS: dict[RunStatus, frozenset[RunStatus]] = {
    RunStatus.CREATED: frozenset(
        {RunStatus.RUNNING, RunStatus.FAILED, RunStatus.CANCELLED}
    ),
    RunStatus.RUNNING: frozenset(
        {
            RunStatus.WAITING_APPROVAL,
            RunStatus.PAUSED,
            RunStatus.FAILED,
            RunStatus.COMPLETED,
            RunStatus.CANCELLED,
        }
    ),
    RunStatus.WAITING_APPROVAL: frozenset(
        {RunStatus.RUNNING, RunStatus.PAUSED, RunStatus.FAILED, RunStatus.CANCELLED}
    ),
    RunStatus.PAUSED: frozenset(
        {RunStatus.RUNNING, RunStatus.FAILED, RunStatus.CANCELLED}
    ),
    RunStatus.FAILED: frozenset(),
    RunStatus.COMPLETED: frozenset(),
    RunStatus.CANCELLED: frozenset(),
}
